import type { ReportDraft } from "@/lib/domain/types";
import { sanitizeReportText } from "@/lib/reports/sanitize";

export function renderReportPdfBytes(report: ReportDraft): Buffer {
  const content = buildPdfContent(report);
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
    `<< /Length ${Buffer.byteLength(content, "latin1")} >>\nstream\n${content}\nendstream`,
  ];
  const chunks = ["%PDF-1.4\n"];
  const offsets = [0];

  for (const [index, object] of objects.entries()) {
    offsets.push(Buffer.byteLength(chunks.join(""), "latin1"));
    chunks.push(`${index + 1} 0 obj\n${object}\nendobj\n`);
  }

  const xrefOffset = Buffer.byteLength(chunks.join(""), "latin1");
  chunks.push(`xref\n0 ${objects.length + 1}\n`);
  chunks.push("0000000000 65535 f \n");

  for (const offset of offsets.slice(1)) {
    chunks.push(`${offset.toString().padStart(10, "0")} 00000 n \n`);
  }

  chunks.push(
    `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`,
  );

  return Buffer.from(chunks.join(""), "latin1");
}

export function buildReportEmail({
  report,
  downloadUrl,
}: {
  report: ReportDraft;
  downloadUrl: string;
}) {
  const subject = sanitizeReportText(`${report.clientName} ${report.periodLabel} maintenance report`);
  const coverageLine = buildCoverageLine(report);
  const text = [
    subject,
    "",
    sanitizeReportText(report.summary),
    coverageLine,
    "",
    `Download: ${downloadUrl}`,
  ].join("\n");
  const html = `
    <div>
      <h1>${escapeHtml(subject)}</h1>
      <p>${escapeHtml(sanitizeReportText(report.summary))}</p>
      <p>${escapeHtml(coverageLine)}</p>
      <p><a href="${escapeHtml(downloadUrl)}">Download the PDF report</a></p>
    </div>
  `;

  return { subject, text, html };
}

export function buildReportPdfAttachment({
  report,
  pdfBytes,
}: {
  report: ReportDraft;
  pdfBytes: Buffer;
}) {
  return {
    filename: `${buildSafeFilenameStem(`${report.clientName}-${report.period}-maintenance-report`)}.pdf`,
    content: pdfBytes,
    contentType: "application/pdf",
  };
}

function buildPdfContent(report: ReportDraft): string {
  const commands = [
    fillRect({ x: 0, y: 0, width: 612, height: 792, color: "0.985 0.982 0.975" }),
    fillRect({ x: 0, y: 684, width: 612, height: 108, color: "0.93 0.91 1" }),
    drawText("TuesdayOps maintenance report", { x: 44, y: 748, size: 22, font: "F2" }),
    drawText(`${report.clientName} ${report.periodLabel} Report`, { x: 44, y: 722, size: 13, font: "F1" }),
    drawText(`Prepared for ${report.clientName}`, { x: 372, y: 748, size: 10, font: "F2" }),
    drawText(`Report period: ${report.periodLabel}`, { x: 372, y: 730, size: 10, font: "F1" }),
    drawText("Generated from stored workflow checks, issues, and synthetic test runs", {
      x: 372,
      y: 712,
      size: 8,
      font: "F1",
    }),
    drawSectionHeading("Executive summary", 44, 650),
    drawWrappedText(sanitizeReportText(report.summary), { x: 44, y: 628, size: 10, width: 88 }),
    drawWrappedText(buildCoverageLine(report), { x: 44, y: 590, size: 9, width: 88 }),
    drawSectionHeading("Operations scorecard", 44, 546),
    ...drawMetricCard({
      x: 44,
      y: 468,
      label: "Workflows monitored",
      value: String(report.metrics.workflowsMonitored),
      detail: "Included in reports",
    }),
    ...drawMetricCard({
      x: 176,
      y: 468,
      label: "Checks run",
      value: String(report.metrics.checksRun),
      detail: "Stored this period",
    }),
    ...drawMetricCard({
      x: 308,
      y: 468,
      label: "Pass rate",
      value: `${report.metrics.passRate}%`,
      detail: "Healthy check runs",
    }),
    ...drawMetricCard({
      x: 440,
      y: 468,
      label: "Issues resolved",
      value: String(report.metrics.issuesResolved),
      detail: "Closed this period",
    }),
    drawSectionHeading("Value delivered", 44, 422),
    drawWrappedText(buildValueDeliveredLine(report), { x: 44, y: 400, size: 10, width: 88 }),
    drawSectionHeading("Report sections", 44, 342),
    ...drawReportItems(report),
    drawSectionHeading("Next actions", 332, 342),
    ...drawRecommendations(report),
    drawLine({ x1: 44, y1: 58, x2: 568, y2: 58, color: "0.82 0.82 0.84" }),
    drawText("Client-safe report generated by TuesdayOps. Raw payloads, secrets, and internal notes are excluded.", {
      x: 44,
      y: 40,
      size: 8,
      font: "F1",
    }),
  ];

  return commands.join("\n");
}

function drawReportItems(report: ReportDraft): string[] {
  const commands: string[] = [];
  let y = 318;

  for (const item of report.items.slice(0, 4)) {
    commands.push(drawText(sanitizeReportText(item.title), { x: 44, y, size: 9, font: "F2" }));
    commands.push(drawWrappedText(sanitizeReportText(item.body), { x: 44, y: y - 16, size: 8, width: 42 }));
    y -= 54;
  }

  return commands;
}

function drawRecommendations(report: ReportDraft): string[] {
  const commands: string[] = [];
  let y = 318;

  for (const recommendation of report.recommendations.slice(0, 4)) {
    commands.push(drawWrappedText(`- ${sanitizeReportText(recommendation)}`, { x: 332, y, size: 8, width: 38 }));
    y -= 42;
  }

  return commands;
}

function drawMetricCard({
  x,
  y,
  label,
  value,
  detail,
}: {
  x: number;
  y: number;
  label: string;
  value: string;
  detail: string;
}): string[] {
  return [
    fillRect({ x, y, width: 116, height: 58, color: "1 1 1" }),
    drawLine({ x1: x, y1: y, x2: x + 116, y2: y, color: "0.86 0.84 0.9" }),
    drawText(label, { x: x + 10, y: y + 38, size: 7, font: "F1" }),
    drawText(value, { x: x + 10, y: y + 19, size: 16, font: "F2" }),
    drawText(detail, { x: x + 10, y: y + 8, size: 7, font: "F1" }),
  ];
}

function drawSectionHeading(text: string, x: number, y: number): string {
  return drawText(text, { x, y, size: 12, font: "F2" });
}

function buildValueDeliveredLine(report: ReportDraft): string {
  return [
    `${report.metrics.issuesResolved} ${pluralize("issue", report.metrics.issuesResolved)} resolved before the next client report`,
    `${report.metrics.issuesCaught} ${pluralize("issue", report.metrics.issuesCaught)} caught by workflow monitoring`,
    `${report.metrics.testFailures} synthetic ${pluralize("failure", report.metrics.testFailures)} surfaced for QA follow-up`,
  ].join("; ");
}

function buildCoverageLine(report: ReportDraft): string {
  return `Monitoring coverage: ${report.metrics.workflowsMonitored} ${pluralize("workflow", report.metrics.workflowsMonitored)}, ${report.metrics.checksRun} ${pluralize("check", report.metrics.checksRun)}, ${report.metrics.testRuns} synthetic ${pluralize("run", report.metrics.testRuns)}`;
}

function pluralize(noun: string, count: number): string {
  return count === 1 ? noun : `${noun}s`;
}

function buildSafeFilenameStem(value: string): string {
  const stem = sanitizeReportText(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 96);

  return stem || "maintenance-report";
}

function wrapLine(line: string): string[] {
  const output: string[] = [];
  let remaining = line;

  while (remaining.length > 88) {
    output.push(remaining.slice(0, 88));
    remaining = remaining.slice(88);
  }

  output.push(remaining);
  return output;
}

function drawWrappedText(
  text: string,
  {
    x,
    y,
    size,
    width,
  }: {
    x: number;
    y: number;
    size: number;
    width: number;
  },
): string {
  const lines = wrapLineToWidth(text, width);

  return [
    "BT",
    `/F1 ${size} Tf`,
    `${x} ${y} Td`,
    ...lines.map((line) => `(${escapePdfText(line)}) Tj T*`),
    "ET",
  ].join("\n");
}

function wrapLineToWidth(line: string, width: number): string[] {
  if (!line) {
    return [""];
  }

  const output: string[] = [];
  const words = line.split(" ");
  let current = "";

  for (const word of words) {
    if (!current) {
      current = word;
      continue;
    }

    if (`${current} ${word}`.length > width) {
      output.push(...wrapLine(current));
      current = word;
    } else {
      current = `${current} ${word}`;
    }
  }

  output.push(...wrapLine(current));

  return output;
}

function drawText(
  text: string,
  {
    x,
    y,
    size,
    font,
  }: {
    x: number;
    y: number;
    size: number;
    font: "F1" | "F2";
  },
): string {
  return ["BT", `/${font} ${size} Tf`, `${x} ${y} Td`, `(${escapePdfText(sanitizeReportText(text))}) Tj`, "ET"].join(
    "\n",
  );
}

function fillRect({
  x,
  y,
  width,
  height,
  color,
}: {
  x: number;
  y: number;
  width: number;
  height: number;
  color: string;
}): string {
  return `${color} rg\n${x} ${y} ${width} ${height} re f`;
}

function drawLine({
  x1,
  y1,
  x2,
  y2,
  color,
}: {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  color: string;
}): string {
  return `${color} RG\n0.8 w\n${x1} ${y1} m\n${x2} ${y2} l\nS`;
}

function escapePdfText(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
